import type { ComponentType } from 'react';
import { Check, Gamepad2, Gem, Layers3, Sparkles, Swords } from 'lucide-react';

type IconType = ComponentType<{ className?: string }>;
type Feature = { title: string; description: string; icon: IconType };
type Plan = { name: string; price: string; source: string; featured?: boolean; features: string[] };

const plans: Plan[] = [
  { name: 'لعبة 2D بدون سورس كود', price: '15,000 جنيه', source: 'بدون تسليم سورس كود', features: ['تصميم ثنائي الأبعاد للمراحل والشخصيات.', '12 رحلة مرتبطة بالعطور المختارة.', 'تسليم النسخة النهائية القابلة للنشر فقط.'] },
  { name: 'لعبة 2D بسورس كود', price: '30,000 جنيه', source: 'يشمل سورس كود اللعبة', features: ['كل مميزات خيار 2D.', 'تسليم سورس كود منظم مع المشروع.', 'مرونة أكبر في التطوير والتعديلات المستقبلية.'] },
  { name: 'لعبة 3D بدون سورس كود', price: '25,000 جنيه', source: 'بدون تسليم سورس كود', featured: true, features: ['تصميم ثلاثي الأبعاد للشخصيات والعوالم.', '12 رحلة مستوحاة من تركيبات العطور.', 'تسليم النسخة النهائية القابلة للنشر فقط.'] },
  { name: 'لعبة 3D بسورس كود', price: '35,000 جنيه', source: 'يشمل سورس كود اللعبة', features: ['كل مميزات خيار 3D.', 'تسليم سورس كود كامل للمشروع.', 'أفضل خيار للتوسع وإضافة محتوى جديد لاحقًا.'] },
];

const gameFeatures: Feature[] = [
  { title: '12 عطرًا، 12 تجربة', description: 'يختار اللاعب أحد العطور، ثم يخوض رحلة مرتبطة به لاكتشاف مكوناته الأساسية.', icon: Gem },
  { title: 'تحديات للوصول للمكونات', description: 'يحارب اللاعب ويتخطى العقبات للوصول إلى نوتات العطر ومكوناته في كل مرحلة.', icon: Swords },
  { title: 'تجربة تحمل هوية العلامة', description: 'الألوان والعوالم والشخصيات تُصمم بما يتناسب مع هوية شركة العطور وقصتها.', icon: Sparkles },
];

const paymentSteps = ['25% مقدم عند بدء المشروع.', '25% عند اعتماد التصميم والشكل العام للعبة.', '25% عند تسليم النسخة التجريبية.', '25% عند التسليم النهائي وقبل النشر.'];

export default function App() {
  return <div className="min-h-screen bg-[#f8fafc] text-slate-800" dir="rtl">
    <header className="border-b border-slate-200/80 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-5"><img src="/logo.png" alt="Penta-k" className="h-10 w-auto object-contain" /><div className="text-left"><p className="text-xs font-semibold tracking-[0.12em] text-sky-700">عرض فني ومالي</p><p className="mt-1 text-sm text-slate-500">لعبة تفاعلية لشركة عطور</p></div></div></header>
    <main className="mx-auto max-w-6xl px-6 py-10 md:py-14">
      <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-7 py-12 text-white shadow-2xl md:px-12 md:py-16"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-fuchsia-500/20 blur-3xl" /><div className="absolute -bottom-24 left-1/3 h-60 w-60 rounded-full bg-amber-400/20 blur-3xl" /><div className="relative max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-fuchsia-100"><Gamepad2 className="h-4 w-4" />تجربة تفاعلية لعشاق العطور</div><p className="mb-3 text-sm font-medium text-fuchsia-300">عرض سعر لتطوير لعبة مخصصة</p><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">رحلة اكتشاف العطر</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300 md:text-xl">لعبة تفاعلية تجعل اللاعب يختار عطره، ثم يخوض تحديات ومعارك للوصول إلى مكونات هذا العطر واكتشاف قصته بطريقة ممتعة.</p><div className="mt-9 flex flex-wrap gap-3 text-sm"><Pill label="12 عطرًا" /><Pill label="مراحل وتحديات" /><Pill label="هوية بصرية مخصصة" /></div></div></section>
      <section className="grid gap-5 py-10 sm:grid-cols-3"><Stat label="عدد العطور" value="12 عطرًا" /><Stat label="فكرة اللعبة" value="قتال واكتشاف" /><Stat label="منصات النشر" value="Apple و Google Play" /></section>
      <section className="mb-10 grid gap-8 rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 md:grid-cols-[1.25fr_0.9fr] md:p-10"><div><Eyebrow text="فكرة اللعبة" /><h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">لكل عطر عالمه ومكوناته</h2><p className="mt-5 max-w-2xl leading-8 text-slate-600">تبدأ التجربة باختيار العطر المفضل. يدخل اللاعب بعدها إلى عالم مستوحى من رائحة العطر، ويقاتل ويتجاوز العقبات حتى يصل إلى المكونات التي تكوّن تركيبته، مثل النوتات العلوية والقلب والقاعدة.</p></div><div className="rounded-2xl bg-fuchsia-50 p-6"><Eyebrow text="مكونات التجربة" /><h3 className="mt-2 text-xl font-semibold text-slate-900">محتوى مصمم للعلامة</h3><div className="mt-5 space-y-3"><CheckRow text="شخصية لاعب وعناصر بصرية مخصصة." /><CheckRow text="مراحل مرتبطة بكل عطر ومكوناته." /><CheckRow text="شاشة اختيار العطور وتقدّم اللاعب." /></div></div></section>
      <section className="mb-10"><SectionTitle eyebrow="نطاق التنفيذ" title="تجربة لعبة متكاملة من الاختيار حتى اكتشاف المكونات" /><div className="grid gap-4 md:grid-cols-3">{gameFeatures.map((feature) => <FeatureCard key={feature.title} feature={feature} />)}</div></section>
      <section className="mb-10 rounded-[2rem] border border-fuchsia-200 bg-gradient-to-l from-fuchsia-50 to-amber-50 p-7 md:p-10"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="max-w-3xl"><Eyebrow text="توصيتنا" /><h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">نرشح تنفيذ اللعبة بتقنية 3D</h2><p className="mt-4 leading-8 text-slate-600">تقنية 3D ستُظهر العطور وعوالمها بشكل أجمل وأكثر جذبًا، وتمنح اللاعب إحساسًا أقوى بالمغامرة؛ لذلك هي الأنسب لهذا النوع من التجارب.</p></div><div className="w-fit rounded-2xl bg-white p-4 text-fuchsia-700 shadow-sm"><Layers3 className="h-10 w-10" /></div></div></section>
      <section className="mb-10"><SectionTitle eyebrow="العرض المالي" title="اختر مستوى التنفيذ المناسب" /><div className="grid gap-6 lg:grid-cols-2">{plans.map((plan) => <PlanCard key={plan.name} plan={plan} />)}</div></section>
      <section className="mb-10 rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 md:p-10"><SectionTitle eyebrow="الدفعات والتسليم" title="تقسيم الدفعات" /><p className="mb-6 max-w-3xl text-sm leading-6 text-slate-600">يُطبق نفس نظام الدفعات على الخيار الذي يتم اختياره.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{paymentSteps.map((step, index) => <article key={step} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><span className="text-sm font-semibold text-fuchsia-700">0{index + 1}</span><p className="mt-4 text-sm leading-6 text-slate-700">{step}</p></article>)}</div></section>
      <section className="rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 md:p-10"><SectionTitle eyebrow="رسوم النشر" title="متطلبات النشر السنوية" /><div className="grid gap-4 md:grid-cols-2"><CheckRow text="رسوم حسابات النشر على Apple App Store وGoogle Play: 50 دولار سنويًا." /><CheckRow text="رسوم النشر السنوية وخدمات الطرف الثالث تُدفع من العميل بشكل منفصل عن قيمة التطوير." /></div></section>
    </main>
    <footer className="mt-12 border-t border-slate-200 bg-white px-6 py-8 text-center text-sm text-slate-500"><p className="font-semibold text-slate-800">Penta-k</p><p className="mt-1">شكرًا لثقتكم، ونتطلع لتقديم تجربة عطرية لا تُنسى.</p></footer>
  </div>;
}

function Eyebrow({ text }: { text: string }) { return <p className="text-sm font-semibold tracking-[0.14em] text-fuchsia-700">{text}</p>; }
function Pill({ label }: { label: string }) { return <span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-slate-100">{label}</span>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{value}</p></div>; }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-7"><Eyebrow text={eyebrow} /><h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{title}</h2></div>; }
function FeatureCard({ feature }: { feature: Feature }) { const Icon = feature.icon; return <article className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="inline-flex rounded-xl bg-fuchsia-50 p-3 text-fuchsia-700"><Icon className="h-6 w-6" /></div><h3 className="mt-5 text-lg font-semibold text-slate-950">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{feature.description}</p></article>; }
function CheckRow({ text }: { text: string }) { return <div className="flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-fuchsia-600" />{text}</div>; }
function PlanCard({ plan }: { plan: Plan }) { return <article className={`rounded-[2rem] border p-7 ${plan.featured ? 'border-fuchsia-200 bg-fuchsia-50 shadow-lg shadow-fuchsia-100/50' : 'border-slate-200 bg-white shadow-sm'}`}><div className="flex items-start justify-between gap-4"><div><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${plan.featured ? 'bg-fuchsia-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{plan.featured ? 'الخيار المُرشّح' : plan.source}</span><h3 className="mt-4 text-2xl font-semibold text-slate-950">{plan.name}</h3></div><p className="whitespace-nowrap text-3xl font-semibold text-slate-950">{plan.price}</p></div><p className="mt-3 text-sm font-medium text-slate-500">{plan.source}</p><div className="mt-6 space-y-3 border-t border-slate-200 pt-6">{plan.features.map((feature) => <div key={feature} className="flex items-start gap-3 text-sm leading-6 text-slate-700"><Check className="mt-1 h-4 w-4 shrink-0 text-fuchsia-600" />{feature}</div>)}</div></article>; }
